# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
  inline_example:
    executors:
      default:
        description: |
          Custom Docker image with pre-packaged welcome orb commands
        docker:
        - image: google/cloud-sdk
    jobs:
      my_inline_job:
        description: |
          Example of a inline orb creation.
        executor: default
        parameters:
          greeting_name:
            description: # a helpful description
            type: string
            default: josh
        steps:
          - my_inline_command:
              greeting_name: <<parameters.greeting_name>>
          - check_ip:
    commands:
      my_inline_command:
        parameters:
          greeting_name:
            type: string
        steps:
          - run: echo "hello <<parameters.greeting_name>>, from the inline command"
      check_ip:
        steps:
          - run:
              name: Getting circleci ip
              command: |
              circle_ci_ip=$(wget -qO- http://checkip.amazonaws.com)
              echo "Circle CI public IP is $circle_ci_ip"

# Orchestrate or schedule a set of jobs
workflows:
  welcome:
    jobs:
      - welcome/run
      - inline_example/my_inline_job:
          name: mybuild
          greeting_name: josh
